### ISSUE TITLE
Changes to owned notification entities may not get detected automatically

### ISSUE THREAD

**Issue by hamiddd1980** [dotnet/efcore#19846]
Hello.I use EF Core in WPF to implement MVVM pattern, but I think there is a problem in Saving New Created Related Entities .
I Load Parent and It's related children Entities from Database using **Include** , **Load** ,**Local** and **ToObservableCollection** to use them in WPF (MVVM pattern). No Problem until here. When I create a new Child Entity  and a new Parent Entity and then I add new Child Entity to Parent's collection , **the new added Child Entity is not tracked by ChangeTracker and so the new child isn't saved to Database when DbContext.SaveChanges is Callled.**

In Fact, I think new added Child Entites should be saved in database with it's Parent after calling DbContext.SaveChanges , but it doesn't happen. 
### Steps to reproduce

1-Define Parent and Child Entity Models:
```C#
public class Parent{
   public Id { get ; set;}
   public string ParentFamily {get; set;}
   public ObservableCollection<Child> Children {get ; set;}
   public Parent(){
       Children =new ObservableCollection<Child>();
   }
}

public class Child{
   public int Id {get ;set;}
   public string FirstName {get;set;}
   public Parent Parent {get; Set;}
}
```
2-Load Parent and It's related Children Entities:
```C#
MyDbContext.Parents
               .Include(p => p.Children)
                .Load();
   var loadedParents =MyDbContext.Parts
                      .Local.ToObservableCollection();
```
2-Create a new Parent and a new Child ,then add the new child entity to the newly created parent:
```C#
Child newChild=new Child{FirstName="David"}; //create a new Child object
Parent newParent=new Parent{ParentFamily ="Williams"};//create a new Parent object
newParent.Children.Add(newChild); //add new child to Parent

 loadedParents.Add(newParent);//add new Parent to Loaded Parents (from previous paragraph)
```
3.Try to save the above changes by calling
```C#
MyDbContext.SaveChanges();//Save Changes
```
4-The problem is that : **the new added Child record is not saved to database .Inspectiong the Changetracker from DbContext also reveals that the new added Child Record is not TRACKED by DbContext.**

5-My questions:

5-1)Why the above problem happens?(Child entity is not tracked by DbContext and not Save to database)

5-2)according to the fact that I use Load and Local properties of DbContext to load Records from Database ,how can I Add New Records To Child Entities And Save Them In Database?
### Further technical details

EF Core version: 3.1
Database provider: (Microsoft.EntityFrameworkCore.SqlServer ,Microsoft.EntityFrameworkCore.Sqlite )
Target framework: (.NET Core 3.0 and .NET Core 3.1)
Operating system: Windows 10
IDE: (e.g. Visual Studio 2019 16.5.0)

**Comment by ajcvickers** [comment]
@hamiddd1980 This looks like a bug. One workaround is to add the child explicitly to its own local collection. Something like:

```C#
var loadedParents = context.Parents.Local.ToObservableCollection();
var loadedChildren = context.Set<Child>().Local.ToObservableCollection();

var newChild = new Child {FirstName = "David"};
var newParent = new Parent {ParentFamily = "Williams"};
newParent.Children.Add(newChild);

loadedParents.Add(newParent);
loadedChildren.Add(newChild);

context.SaveChanges();
```
----

Note for team: I am able to reproduce this on 3.1 and latest daily build. Runnable repro:

```C#
public class SomeDbContext : DbContext
{
    private static readonly ILoggerFactory
        Logger = LoggerFactory.Create(x => x.AddConsole());//.SetMinimumLevel(LogLevel.Debug));

    public DbSet<Parent> Parents { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseLoggerFactory(Logger)
            .EnableSensitiveDataLogging()
            .UseSqlServer(Your.SqlServerConnectionString);
}

public static class ThreeOne
{
    public static void Main()
    {
        using (var context = new SomeDbContext())
        {
            context.Database.EnsureDeleted();
            context.Database.EnsureCreated();

            context.Parents.Include(p => p.Children).Load();

            var loadedParents = context.Parents.Local.ToObservableCollection();

            var newChild = new Child {FirstName = "David"};
            var newParent = new Parent {ParentFamily = "Williams"};
            newParent.Children.Add(newChild);

            loadedParents.Add(newParent);

            context.SaveChanges();
        }
    }
}

public class Parent
{
    public int Id { get; set; }
    public string ParentFamily { get; set; }
    public ICollection<Child> Children { get; } = new List<Child>();
}

public class Child
{
    public int Id { get; set; }
    public string FirstName { get; set; }
    public Parent Parent { get; set; }
}
```

**Comment by AndriySvyryd** [comment]
I wonder if the behavior depends on what `context.ChangeTracker.DeleteOrphansTiming` and `context.ChangeTracker.CascadeDeleteTiming` are set to

**Comment by hamiddd1980** [comment]
Hello. I would appreciate your immediate attention to this matter.
I also checked the **Delete** and **Update** actions and I noticed that these two actions works well without problem.(changes on the children entities are saved to Database after Calling SaveChanges on DbContext):
1-Delete:
```
Parent loadedParentFromDb = Parents.FirstOrDefault();
Child firstChild = loadedParentFromDb.Children.FirstOrDefault();
loadedParentFromDb.Children.Remove(firstChild);
ParentDbContext.SaveChanges();//Deleted Child is Removed from Database
```
2-Update :

```
Parent loadedParentFromDb = Parents.FirstOrDefault();
Child firstChild = loadedParentFromDb .Children.FirstOrDefault();
firstChild.ChildName = "Sara";
ParentDbContext.SaveChanges();//changes to Child Entity is Saved to Database
```
I would appreciate it if you would implement the mentioned behavior for **Add action**. I mean by calling **DbContext.savechanges** , all new Entities(Parent and it's related new entities) save in the Database.
Thank you for your help..

**Comment by ajcvickers** [comment]
@AndriySvyryd It doesn't appear to be dependent on the cascade timings.

@hamiddd1980 This has been reproduced as a bug and it is currently planned to be fixed in the next non-patch release. I suggested above a workaround you can try in the meantime. If the workaround doesn't help, then please let us know and include details.

**Comment by aarondglover** [comment]
Why not fix this in a patch release??? is it because there is a work around available?

This bug affects a pretty fundamental use case that users of EF write every single day. It has just wasted 3 hours of my life that I'm not getting back

**Comment by ajcvickers** [comment]
@aarondglover The [release planning process](https://docs.microsoft.com/en-us/ef/core/what-is-new/release-planning) describes how we decide what to patch.

**Comment by aarondglover** [comment]
Thanks @ajcvickers 

With regard to the criteria;

- [x] It is impacting multiple customers
- [x] It is a regression from a previous release
- [ ] The failure causes data corruption

**One  could argue data corruption has occurred when it means state is not being persisted/saved. If this is accepted then all three criteria have been met.**

We are less likely to patch an issue if:

- [x] There are reasonable workarounds 
- [ ] The fix has high risk of breaking something else
- [ ] The bug is in a corner-case

- "Reasonable" is subjective. The current workaround means technical debt in my projects which need to be addressed at a later point
- I can't speak to the second point
- I don't believe this is a corner-case.

Feels like this possibly should be in a patch release. 

The point as to whether this will be a Patch release or not is largely esoteric. What I am more interested in is when is the next release that will fix this issue planned? Has this issue made it into a sprint?

**Comment by ajcvickers** [comment]
@hamiddd1980 We will consider it for a patch. However, please note that the earliest this is likely to appear in a patch release is June. This is because EF Core is tied to the .NET Core patch process, which is somewhat slow. Also, it will need to get approved for a patch by the directors. The case is quite weak right now with only two customers and a workaround. It would help if you could provide more details on why the workaround isn't sufficient.

**Comment by aarondglover** [comment]
Appreciate giving this consideration for a patch.

How could this possibly be affecting only two customers? Don't conflate the people who bother to report the issue with the number of people affected.

This is such a fundamental use case and the natural way to use the product that this must be affecting more people.

**Comment by julielerman** [comment]
Since I've been called out here I want to verify the use case. Adding a new graph to a DBSet still works for me. So is this specifically when the new graph to the observable collection? I can add a note about this to the course but want to be sure I understand the specific scenario. THanks.

**Comment by ajcvickers** [comment]
@julielerman Yes, this is specifically about it happening with owned entities and an ObservableCollection. It's not a mainline scenario.

@aarondglover Yes, when I say two customers, I mean reported by two customers. It's actually incredibly difficult to extrapolate this to the real number of people impacted, but two reports from monthly usage in the hundreds of thousands of developers is still low. That being said, two reports can be enough to cover the multiple customers criterion, assuming the other criteria are also met. The most significant of these is whether or not the workaround is reasonable, which it seems to be the case here. If the workaround isn't reasonable for you, then can you provide details as to why not?

**Comment by tvkit** [comment]
> the new added Child Entity is not tracked by ChangeTracker and so the new child isn't saved to Database when DbContext.SaveChanges is Callled.

I had a similar issue with SQL 2019.  I determined the data wasn't persisting simply by running related queries within SQL Studio.  I used the following [option](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.dbcontextoptionsbuilder.enableserviceprovidercaching?view=efcore-3.1) to mitigate the unexpected behavior:

```
services.AddDbContext<MyDbContext>(options =>
      {
        options.EnableServiceProviderCaching(false);
      }, ServiceLifetime.Scoped);
```

I'm using the option as work-around, not a solution. Will revisit when time permits.

**Comment by julielerman** [comment]
I propose changing the title of this issue to indicate the edge-case nature of the problem since it sounds alarming otherwise. :)
