### ISSUE TITLE
Ability to map a CLR method returning queryable to TVF

### ISSUE THREAD

**Issue by smitpatel** [dotnet/efcore#20051]
Split off from #4319

```C#
            public IQueryable<OrderByYear> GetCustomerOrderCountByYear(int customerId)
            {
                return CreateQuery(() => GetCustomerOrderCountByYear(customerId));
            }
```
Above when used in LINQ will insert query root for `OrderByYear` alongwith TVF as SQL translation.

It also bootstrappable. So you don't need to create query root.

Pending items
- [x] Map an entityType to TVF.
  - [x] Ignore entity types mapped to TVF in migrations (don't map them to a table by default)
  - [x] Query will use TVF whenever this query root is used.
- [x] Convention to register keyless entity type returned by function.
- [x] Store mapped EntityType in the IDbFunction (#20160)
- [x] Refactor IDbFunction metadata
  - Additional metadata to map queryable function related task
  - Store all functions in a single annotation
  - Dual facets for queryable & scalar functions
  - IDbFunction without method info
  - (Essentially make IDbFunction a TVF in "relational model"
- [x] Query translation
- [ ] Apply null semantics processing to QueryableFunctionExpression (#20180)
- [x] IDbFunction.HasTranslation API needs improvement (#20163)
- [x] Consider a way to represent query roots which are custom like FromSql/Queryble method call (#20146)

**Comment by roji** [comment]
Adding providers-beware for the tests

**Comment by smitpatel** [comment]
Don't leak DbContext in query cache for queryable functions.
