### ISSUE TITLE
Define consistent behaviors for FromSql methods used against complex mappings

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#21888]
For example, what shape is the query expected to return for entity types mapped in different ways, such as TPT vs TPH.

Issues that we're currently tracking in this area:

- [ ] #4976 FromSql(): Support passing a preamble SQL string
- [ ] #17215 Support FromSql with table splitting
- [ ] #18616 FromSql() and owned type with table splitting
- [ ] #21627 Enable flexible FromSql mapping
- [ ] #21781 FromSql with auto-included navigations sharing same table
- [ ] #21826 API to check expected shape of FromSql
