### ISSUE TITLE
Improve experience for managing migrations

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#22945]
This is a tracking issue for the overall experience.

- [ ] Squash migrations #2174
- [ ] A command to upgrade snapshots and backing models #18557
- [ ] More specific provider capabilities 
- [ ] Modernize tooling
- [ ] Adhere to stdout/stderr conventions #22878
- [ ] Allow migrations configuration to be automatically be picked up from a cloned repo #20862
- [ ] Migrations Projects #19694
- [ ] Improve existing database support #2167

**Comment by jerriep** [comment]
I am very happy to see some improvements around migrations, especially the squashing of migrations. Thank you for looking into that one!
