### ISSUE TITLE
Improve Migrations data seeding

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#22947]
This an "epic" issue for the theme of improving seed data in migrations. Specific pieces of work will be tracked by linked issues.

----

- [ ] Data Seeding: Generate leaner SQL #9998
- [ ] Data Seeding: Add sugar for shadow properties #9999
- [ ] Data Seeding: Add support for navigations #10000
- [ ] Migrations don't use parameters for data operations #20734
- [ ] Log when data seeding needs to recreate a row #21823

**Comment by maimonieli** [comment]
Hi , 
composed types data seeding it's a very important issue in our application. 
any updates / alternatives ?
