### ISSUE TITLE
Improve the Microsoft.Data.Sqlite ADO.NET provider

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#22949]
This an "epic" issue for the Microsoft.Data.Sqlite ADO.NET provider. Specific pieces of work will be tracked by linked issues.

----

- [ ] Check commands[i] is not null for avoid NPE on Dispose command #22921
- [ ] Microsoft.Data.Sqlite: Add Default Timeout connection string keyword #22505
- [ ] SQLite: Use multi-threaded mode by default #22330
- [ ] Implement SqliteException.SqlState #21599
- [ ] Implement SqliteException.IsTransient #21598
- [ ] Sqlite: add transaction savepoint API #20228
- [ ] Case-sensitive parameter names #18861
- [ ] Use Span overload of sqlite3_prepare_v2 #16202
- [ ] Add Span overloads to SqliteBlob #16187
- [ ] Persist prepared statements across commands #14044
- [ ] No SqliteDataAdapter #13838
- [ ] Pool Connections #13837
- [ ] Authorization Callbacks #13835
- [ ] BackupDatabase() should yield #13834
- [ ] Feature request: tracing, debugging #13832
- [ ] Implement Data Change Notifications Callback #13827
- [ ] Support System.Transactions #13825
- [ ] Virtual table modules #13823

**Comment by roji** [comment]
Moved transaction savepoint API (#20228) up to proposed as there's a PR already out (#22869).
