### ISSUE TITLE
Miscellaneous improvements to Migrations

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#22946]
This an "epic" issue for the theme of miscellaneous improvements to Migrations. Specific pieces of work will be tracked by linked issues.

----

- [ ] SqlServer Migrations: Rebuild column when IDENTITY changes #2100
- [ ] Migrations: Provider-rendered annotations in code #6546
- [ ] Support ColumnAttibute.Order #10059
- [ ] Add doc comments to migration files, or disable CS1591 #10695
- [ ] Add a warning when store-generated PK is not supported #11162
- [ ] SqlServer Migrations: Rebuild foreign keys #12586
- [ ] Migrations XMLDOC #13955
- [ ] Rebuild column when migrating from computed to non-computed #14075
- [ ] Design: Modernize generated C# #14545
- [ ] Mmigrations are too aggressive on RenameColumn #15178
- [ ] SqlServer Migrations: Rebuild primary keys when column narrowed #16758
- [ ] Migrations: SnapshotModelProcessor not used when generating SQL #18708

**Comment by coffeebe4code** [comment]
Where are we at on [1775](github.com/dotnet/efcore/issues/1775)?

`dotnet ef database update --dry-run`
The reason i ask is because of how important this would be. I would like to know if a dry run would be successful, or if there are blatant errors in cicd a developer has missed.

My plan is to have a developer raise a PR to the Database Project, and with cicd, it use the --dry-run flag. We would do our own validation on the PR, but having a clear understanding that the proposed migration script with it's Up would be successful. It would also be beneficial as it wouldn't commit the transactions since it is an actual PR. If we were so proactive, it would be nice to include the --down flag, to run through both the up and down. But that might be a new feature request.

--dry-run wouldn't commit the transaction, but it would return an error to entity framework it could recognize as every transaction up until this point (the end) was successful. I'm sure you all might have a better design.

But I can't stress how great this would be from a code-first cicd maintenance point of view..

**Comment by roji** [comment]
@coffeebe4code better to post on the specific issue (#1775) rather than here - will minimize the comments to keep things clean.

#1775 has received only 14 upvotes in the 10 years of its life, so it's not important to many users and is therefore currently in the backlog.
