### ISSUE TITLE
Miscellaneous improvements to reverse engineering (a.k.a. scaffolding a DbContext)

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#22948]
This an "epic" issue for the theme of miscellaneous improvements to Migrations. Specific pieces of work will be tracked by linked issues.

----

- [ ] dotnet ef dbcontext scaffold doesn't work with computed columns unless user is db_owner #22842
- [ ] Detect simple join tables in reverse engineering and create many-to-many relationships #22475
- [ ] DatabaseGeneratedAttribute in scaffolded code #22170
- [ ] SqlServer RevEng: Included index columns with renamed properties aren't handled #22150
- [ ] Add option to skip views to Scaffold-dbcontext #21283
- [ ] Scaffolding a database created my EF Core does not have the same DeleteBehaviour #21252
- [ ] Consider using Verbatim String Generation if absolutely sure will not contain linebreaks #20723
- [ ] Can Scaffold-DbContext generate entities with comments #19113\
- [ ] Create CTI test for reverse engineering #15534
- [ ] Scaffolding and C# 8 nullable reference types #15520
- [ ] Reverse engineering rowversion/timestamp on SQL Server should generate ulong property #12435
- [ ] RevEng: Decimal column with same precision and scale as the default produce warnings at runtime #12241
- [ ] Recognize filters created by fluent API and reverse engineer to fluent API. #10183
- [ ] SqlServer RevEng: Scaffold default schema #9318
- [ ] SQLite RevEng: Reverse engineer constraint names #8802
- [ ] RevEng: Generate IEntityTypeConfiguration classes (avoids large OnModelCreating) #8434
- [ ] Reverse Engineer: Table/Schema Exclusion #6182
- [ ] Reverse Engineer: Extensibility points to customize model, code templates, etc #4038
- [ ] Reverse Engineer: Better support for namespaces #3988
- [ ] RevEng: Use EF to load metadata for SqlServer provider #1667

**Comment by ErikEJ** [comment]
#10881 ?

**Comment by w3rm** [comment]
Revisit navigation naming convention when reverse-engineering composite keys #16711
+1

**Comment by AraHaan** [comment]
I will be happy with this one -> SP's being scaffolded even if it requires them being done at the template level.

**Comment by ErikEJ** [comment]
@AraHaan EF Core Power Tools scaffolds stored procedures and their result sets.

**Comment by AraHaan** [comment]
I also created this that *should* hopefully work with EFCore and EF6 out-of-box as well. Well provided the API's have not changed much.

https://github.com/Elskom/EdmxSourceGenerator

How it works:
- It uses a pre-existing ``*.edmx`` file which is in XML format file that I did some research to figure out *most* of what each attribute and element does to provide a similar functionality.

Why is this a thing?
- At one point in Visual Studio's 2022 lifetime there was a bug where if you migrated a .NET Framework project to SDK style but kept it only target .NET Framework that it would break the built in edmx code generator that was built into Visual Studio with errors, as such I decided the best work around for it would be to migrate that generation code to a public github source generator. I also feel like this because it would read the project's ``TargetFramework`` and from there select either EF6 or EFCore code generation which makes migration a 100x easier without needing to learn a command line tool or needing to read documentations to write the code yourself.
