### ISSUE TITLE
Improve support for spatial types

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#22951]
This an "epic" issue for the theme of improving support for spatial types. Specific pieces of work will be tracked by linked issues.

#### Proposed for 6.0

- [ ] Spatial Indexes #12538
- [ ] Translate aggregate functions #13278

#### Backlog

- [ ] Cosmos: Spatial types, functions and spatial indexes #17317
- [ ] SQLite Spatial: Allow specifying a default SRID and dimension #13244
- [ ] Sqlite Spatial RevEng: Column SRID and Dimension not configured #13765
- [ ] Sqlite Spatial RevEng: Ignore empty string column default #13766
- [ ] Upgrade to SpatiaLite 5 #22138

**Comment by wanghanbo** [comment]
Can Sqlite.NetTopologySuite support Geopackage?

**Comment by roji** [comment]
@wanghanbo the Geopackage [home page](https://www.geopackage.org) states that "SpatiaLite now supports GeoPackage as of version 4.2.0" - have you tried to use SpatiaLite and have you encountered issues with it?
