### ISSUE TITLE
Improve the Microsoft.EntityFrameworkCore.Sqlite EF Core database provider

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#22950]
This an "epic" issue for the theme of improving the EF Core provider for SQLIte. Specific pieces of work will be tracked by linked issues.

----

- [ ] Enable Decimal #19635
- [ ] Optimistic Offline Lock #2195
- [ ] HiLo Id generation for Sqlite #20750
- [ ] SQLite full-text search support #4823
- [ ] RevEng: Reverse engineer index filters #8800
- [ ] RevEng: Reverse engineer constraint names #8802
- [ ] RevEng: Sample data to determine CLR type #8824
- [ ] Make AUTOINCREMENT more first-class #10228
- [ ] Translate Guid.NewGuid() #11520
- [ ] Spatial: Allow specifying a default SRID and dimension #13244
- [ ] Spatial RevEng: Column SRID and Dimension not configured #13765
- [ ] Spatial RevEng: Ignore empty string column default #13766
- [ ] Improve the experience for using SQLite in-memory databases #16103
- [ ] Support translation of ToString #17223
- [ ] UseSpatiaLite can translate more Math members #18843
- [ ] Translate TimeSpan members #18844
- [ ] Translate Regex.IsMatch() #18845
- [ ]  Can't insert null into TIMESTAMP coulmn #20475
- [ ] Ensure that EF Core with SQLite is a good experience in Blazor WASM #21101
- [ ] Sqlite create user defined function in model. #21253
- [ ] Upgrade to SpatiaLite 5 #22138
- [ ] Drop/create SQLite columns when changing column type to something not convertible #22598
- [ ] Should string.Contains use LIKE? #22917

**Comment by nolanblew** [comment]
Any update on the progress of this?

**Comment by ErikEJ** [comment]
This? This is an umbrella epic for multiple issues.

**Comment by luoyunchong** [comment]
Any update on UseSpatiaLite?
