### ISSUE TITLE
Improve many-to-many, skip navigations, and indexer properties

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#22960]
This an "epic" issue for the theme of improvements to many-to-many and the constructs from which it is composed. Specific pieces of work will be tracked by linked issues.

#### Proposed for 6.0

- [ ] Detect simple join tables in reverse engineering and create many-to-many relationships #22475
- [ ] Perf testing for many-to-many #21919

#### Backlog

- [ ] Support unidirectional many-to-many relationships through shadow navigations #3864
- [ ] Model "implicit" many-to-many scenarios via readonly navigations #20337
- [ ] Support non-many-to-many skip navigations #21673
- [ ] Create an alternate key for join entity types which have an independent PK #21900
- [ ] Determine how to look up join entity types at model building time #21901
- [ ] Use simple entity type for simple join tables #22000
- [ ] Improve the query generated for many-to-many explicit/lazy load #22022
