### ISSUE TITLE
Improve DbContext configuration and management

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#22961]
This an "epic" issue for the theme of improvements for configuring and managing DbContext instances. Specific pieces of work will be tracked by linked issues.

#### Proposed for 6.0

- [ ] SQL Server: consider adding first class support for SqlConnection.AccessToken for AAD #13261

#### Backlog

- [ ] Ability to register IInterceptor without an IDbContextOptionsExtension #21578
- [ ] Use service to create connections #774
