### ISSUE TITLE
Narrow the feature gap between EF Core and EF6

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#24106]
There are still some scenarios supported on EF6 which aren't on EF Core. In order to make it as easy as possible to transition from EF6 to EF Core, we plan to close this gap as much as possible, although some scenarios will remain unsupported by design.

- [ ] [Query: Expand navigations after GroupBy operator is applied](https://github.com/dotnet/efcore/issues/22609)
- [ ] [Detect simple join tables in reverse engineering and create many-to-many relationships](https://github.com/dotnet/efcore/issues/22475)
- [ ] [Support ability to select top N of each group](https://github.com/dotnet/efcore/issues/13805)
- [ ] [Translate GroupBy followed by FirstOrDefault over group](https://github.com/dotnet/efcore/issues/12088)
- [ ] [Support raw SQL Queries for basic types like Guid, DateTime and int](https://github.com/dotnet/efcore/issues/11624)
- [ ] [Support raw SQL queries without defining an entity type for the result](https://github.com/dotnet/efcore/issues/10753)

**Comment by ankitmatrix08** [comment]
@AndriySvyryd May I know why this has been removed from 7.0.0 milestone as before it was on schedule and confirmed [here](https://github.com/dotnet/efcore/issues/27426#issuecomment-1039477754) ?

**Comment by roji** [comment]
@ankitmatrix08 this has been changed to the "epics" milestone, which is where we track over-arching epics which track specific issues. It's just a "book-keeping" change - the concrete issues tracked here are still in the 7.0 milestone and are still planned (though that doesn't mean all will necessary make it in).

**Comment by roji** [comment]
I personally like to have epics in the milestone, allowing both ourselves and users to track work in the milestone for a high-level item. [Here's how Npgsql does it](https://github.com/npgsql/npgsql/issues?q=is%3Aissue+label%3Aepic+is%3Aclosed+milestone%3A6.0.0) - it's been very useful for me (and hopefully for users) to be able to drill down like this.

For work that's ongoing across multiple versions (e.g. EF6 parity), each milestone epic can smiply reference the one before etc., and we can have one in the backlog for unplanned work.

But we should probably discuss in a design meeting...

**Comment by ankitmatrix08** [comment]
> @ankitmatrix08 this has been changed to the "epics" milestone, which is where we track over-arching epics which track specific issues. It's just a "book-keeping" change - the concrete issues tracked here are still in the 7.0 milestone and are still planned (though that doesn't mean all will necessary make it in).

@roji That's the thing, since it's not clear as to what all items will make it to the 7.0.0 (among ef6-parity) release hence the confusion and trouble for us decide our migration.

**Comment by roji** [comment]
@ankitmatrix08 the milestone on each individual issue determines whether it's in the plan or not. This issue is just a list referencing those issues for easier tracking; we generally update it to keep it in sync, but that may not happen right away. Just check individual issues directly.

**Comment by mairaw** [comment]
I'm cleaning up the .NET 6 project. This shows as completed on the project dashboard but still open here. Not sure if this needs any updates.

**Comment by mairaw** [comment]
Sounds good @roji. Thanks for making the update.
