### ISSUE TITLE
Continue evolving System.Data and the database providers

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#24109]
- [ ] [New System.Data.Common batching API](https://github.com/dotnet/runtime/issues/28633)
- [ ] [Standardize on DiagnosticSource for tracing in System.Data components](https://github.com/dotnet/runtime/issues/22336)
- [ ] [Microsoft.Data.Sqlite: Pool Connections](Microsoft.Data.Sqlite: Pool Connections)
- [ ] [Microsoft.Data.Sqlite: Persist prepared statements across commands](https://github.com/dotnet/efcore/issues/14044)
- [ ] [SqlServer.Core](https://github.com/dotnet/efcore/issues/24108)
