### ISSUE TITLE
NativeAOT work for 9.0

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#29754]
This is a grouping of related issues. Feel free to vote (👍) for this issue to indicate that this is an area that you think we should spend time on, but consider also voting for individual issues for things you consider especially important.

---

#### Query

* [ ] #25009 (@roji)
  * [x] #32999 (@roji)
  * [x] #31331 (@roji)
      * [ ] #33541 (@roji)
  * [x] #33008 (@roji)
  * [ ] #32923 (@maumar/@roji)
      * [x] #33383
  * [x] #33103 (@AndriySvyryd)
* [ ] #32727 (@roji)
* [x] #29753 (@roji)
* [ ] #29759 (@roji)
* [x] https://github.com/dotnet/runtime/issues/79199 (@roji, done in 8.0)
* [x] #29725 (done in 8.0)
* [x] https://github.com/dotnet/runtime/issues/86161 (runtime API to access private fields efficiently, done in 8.0)
* [x] https://github.com/npgsql/npgsql/issues/4764 (done in 8.0)

#### Other

* [ ] #33478 (@AndriySvyryd)
* [x] #29755 (@AndriySvyryd)
* [x] #24896 (@AndriySvyryd)
* [x] #29761 (@AndriySvyryd)
* [ ] Warning/error when not using compiled model with NativeAOT (@AndriySvyryd)
* [ ] Allow to execute migration operations at runtime with #19694
* [ ] #24901

## Out of scope for EF9

* [ ] #33418
* [ ] #29760
    * [ ] #32734
* [ ] #31332
* [ ] #29858
* [ ] #29764
* [ ] #29763
* [ ] #21894
* [ ] #33766
* [ ] Improvements to SQL generation ([#29753](https://github.com/dotnet/efcore/issues/29753)):
    * [ ] #33516
    * [ ] #33508
    * [ ] #33509
* [ ] #33515
* [ ] #33639
* [ ] #33909

**Comment by jeswin** [comment]
I know this is tagged 'consider-for-current-release'. But just to confirm, the plan is to ship it with .Net 8 right?

Upvoted. This is the last major piece required to get native code web apps working without losing out on productivity.

**Comment by roji** [comment]
@jeswin the plan is still to ship **experimental** support, but it's not yet clear what we'll manage to complete before the work window for 8.0 closes.

**Comment by jeswin** [comment]
Thanks for the update.

**Comment by JOULTICOA** [comment]
I opened issue here but maybe that was wrong spot  https://github.com/dotnet/core/issues/8704 @roji 

I see in issue https://github.com/dotnet/efcore/issues/29725  some people said it was now working.  I can't seem to get the Microsoft.Data.SQLite to work with AOT publish.  is there a certain version I should try?

Thank you!

**Comment by roji** [comment]
@JOULTICOA can you please open a new issue in this repo (not dotnet/core), with the exact versions and full error(s) that you're seeing? Ideally, with a minimal code sample as well.
