### ISSUE TITLE
Implement support for the new SQL Server native JSON type

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#32150]
SQL Azure now has the new JSON type as a public preview ([docs](https://learn.microsoft.com/en-us/sql/t-sql/data-types/json-data-type)); the type will also appear in the next on-premise SQL Server version. We should ensure support for this in EF. We likely want to wait until some sort of on-premise SQL Server supports this.

### External things we depend on

- ~~[ ] We're blocked until we're provided a SqlClient version that supports the new JSON type ([tracking issue](https://github.com/dotnet/SqlClient/issues/2622))~~.
  - We can release without a dependency on the new SqlClient. We just need the SqlDbType value from the BCL.
- [x] SqlDbType.Json is being exposed in the runtime for .NET 9.0 ([issue](https://github.com/dotnet/runtime/issues/103925)). EF will presumably need to use that to specify to SqlClient to send the new JSON type.

### TODO

- [x] Implement type mapping support for mapping .NET string to the new json type.
- [x] Allow users to map primitive collections to the new JSON type (by explicitly configuring the column type - we'll consider switching the default later).
- [x] #28452 (to allow users to map owned entity types to the new JSON type).
- [x] Test-wise, we'd ideally duplicate the PrimitiveCollections and other JSON-related tests to also execute when configured with json. Though note that the JSON type is currently only available in SQL Azure, and we don't currently test against it, as there's no local emulator version. 

/cc @saurabh500

**Comment by roji** [comment]
The JSON feature seems to be out (as preview) on Azure SQL, [see docs](https://learn.microsoft.com/en-us/sql/t-sql/data-types/json-data-type?view=azuresqldb-current&viewFallbackFrom=sql-server-ver16).

Some things to think about:
* Should/can we switch to mapping to the new type by default (as opposed to nvarchar(max))?
    * The type is currently only available on Azure SQL, and not on any on-prem SQL Server version. If we decide to change the default, we can do that only when the user uses the new UseAzureSql() instead of UseSqlServer() (not yet implemented, see #33816).
    * We'd need to carefully think of the migration path for users with existing databases, e.g. is it possibly to automatically migrate existing `nvarchar(max)` columns to the new `json` type (and is this something we actually want).
    * This would apply to both owned entity types and primitive collections (which are mapped to JSON columns).
    * Specifically for complex types, we don't currently support mapping these to JSON so it may be easier to map to the new JSON type (no breaking change).

**Comment by ErikEJ** [comment]
@roji Does reverse engineering support Json SQL Server columns? If not, happy to submit a PR

**Comment by roji** [comment]
@ErikEJ let's discuss in #35943.

**Comment by hjrb** [comment]
Use EF Core 9 (latest) and Azure SQL compatability level 170 I get an error message when trying to insert a new record into a table with a json column:
The SqlDbType enumeration value, 35, is invalid. (Parameter 'SqlDbType')
I'm using this connection string
`"Server=tcp:<some Azure SQL server name>;Initial Catalog=<soeme DB Name>;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;Authentication=\"Active Directory Default\";",`
- The EF Core entity class uses data type string? for the json column
- in the DB context the column is configured using
`     entity.Property(e => e.AdditionalData).HasColumnType("json");`

What am I doing wrong?

**Comment by roji** [comment]
@hjrb which version of EF are you using, and which version of SqlClient?

**Comment by hjrb** [comment]
<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.7" />
I have not added SQLClient explicitely. Transitive  uses 5.1.6

**Comment by ErikEJ** [comment]
Try with 6.0.2

**Comment by hjrb** [comment]
I excplictely installed SqlClient 6.02 - that fixes the issue.
Thanks!
