### ISSUE TITLE
Improve multi-tenancy support

### ISSUE THREAD

**Issue by AndriySvyryd** [dotnet/efcore#32371]
This is a grouping of related issues. Feel free to vote (👍) for this issue to indicate that this is an area that you think we should spend time on, but consider also voting for individual issues for things you consider especially important.

---

#### Backlog
- [ ] #8576 would allow to add tenant filter in alongside other filters
- [ ] #17347 would allow to ignore all tenant filters while preserving others
- [ ] #24122 could be used as extra protection against undesired cross-tenant data mutation
- [ ] #30061 to allow easier customization for tenants
- [ ] As an alternative to query filters #9965 could be used
- [ ] #6089 is another alternative with even more isolation
