### ISSUE TITLE
EF Core 9 release checklist

### ISSUE THREAD

**Issue by AndriySvyryd** [dotnet/efcore#32915]
### RC1 (Code-complete)
- [x] API Review
- [ ] Make sure docs for services state the correct lifetime

### RC2
- [ ] #7201
- [x] (@AndriySvyryd) Run SqlServer and Cosmos tests against Azure
- [x] Make sure we depend on LTS SqlClient
- [x] (@cincuranet) #34575
- [x] Make sure we depend on non-preview `Mono.TextTemplating`
- [x] Make sure we depend on the `Microsoft.CodeAnalysis.CSharp.Workspaces` that corresponds to our TFM (e.g. 4.8.0 for net8.0)
- [x] Make sure we depend on the `Microsoft.Extensions.*` versions that correspond to our TFM so that the shared framework is used when the app targets that TFM
- [ ] (@SamMonoRT) Review all of our (transitive) dependencies to make sure that the support policies are aligned
- [x] (@AndriySvyryd) Update threat model, review warnings from CG, NuGet Audit and other validation tools

### GA
- [x] Remove tools workaround (or make it conditional on release type) https://github.com/dotnet/efcore/commit/e9b942badcbe6a24518a1f4953251585e8dad8b7#diff-50e91c82311ea26f2a73202525dfdf2b0a89c178ee666b2bf3ad4c84ac4c06dc
- [x] (@roji) #32293
- [x] Code cleanup
- [x] Verify changes from servicing branches were merged correctly (especially MSRC if any)
- [x] Verify all quirks removed
- [x] (@AndriySvyryd) Setup staging branches for servicing
- [x] (@AndriySvyryd) Update inter-branch and internal mirroring flows
- [x] Update What's New and breaking changes
- [x] Update the ToC to point to the new What's New page
- [x] (@roji) Merge Docs to live
- [x] (@SamMonoRT) Publish API docs
  - [ ] Including the new `Microsoft.EntityFrameworkCore.Tasks` assembly
  - [x] Also for `[Microsoft.Data.Sqlite](https://github.com/dotnet/Microsoft.Data.Sqlite.ApiDocs)`. Looks like we missed this in 8
- [ ] https://github.com/dotnet/EntityFramework.Docs/issues/4837

### Post-release
- [x] (@AndriySvyryd) Delete preview branches and branches for releases that are no longer supported (create tags)
- [x] (@AndriySvyryd) Remove obsolete members in the next release (only the ones made obsolete in an LTS release) https://github.com/dotnet/efcore/issues/34467
- [x] Make sure to target only the latest TFM to make the above 2 items more manageable and simplify the support policy for our users
- [x] Update .NET SDK version
- [x] Create repo survey issue
- [x] Create a checklist for 10

**Comment by bricelam** [comment]
- [ ] Make sure you depend on a SQLite version that supports .NET 9 Wasm

**Comment by AndriySvyryd** [comment]
@bricelam That sounds like a feature request unless we already support Wasm. Can you provide more context?

**Comment by bricelam** [comment]
In the past, I’ve coordinated with Eric to update the wasm builds of SQLitePCLRaw. They need to be updated every release since Emscripten isn’t backwards compatible with old binaries.
